name: call_api_from_cli
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: User API
        run: |
          gh api -X GET   /users/${{ github.triggering_actor }} --jq .name
      - name: user
        run: |
          git config user.email "$(git log -n 1 --pretty=format:%ae)"

      - name: get email
        id: test
        uses: evvanErb/get-github-email-by-username-action@v1.25
        with:
          github-username: ${{ github.triggering_actor }}
          
      # Use the output from the `test` step
      - name: Print the found email
        run: echo "The email is ${{ steps.test.outputs.email }}" # Example of how to access output email
    env:
       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

